import { DesignCanvasApp, MoodboardApp } from './design/DesignApp.js';
import { FinderApp } from './finder/FinderApp.js';
import { ChatApp, MeetingApp, MinutesApp, SpeakerApp } from './meeting/MeetingApp.js';
import { NotesApp, PaperApp, TranslateApp } from './paper/PaperApp.js';
import { EditorApp, TutorialGuideApp } from './tutorial/TutorialApp.js';
import { createAppHost, type AppManifest } from './manifest.js';

export const APP_CATALOG: AppManifest[] = [
  {
    id: 'finder-desktop',
    title: 'Finder — Desktop',
    subtitle: 'Files',
    icon: '🖥',
    accent: '#4ea1ff',
    semanticTags: ['files', 'source'],
    minSize: { width: 420, height: 280 },
    defaultSize: { width: 640, height: 420 },
    scenario: 'files',
    component: (props) => <FinderApp {...props} variant="desktop" />,
  },
  {
    id: 'finder-submission',
    title: 'Finder — Submission',
    subtitle: 'Files',
    icon: '📬',
    accent: '#4ea1ff',
    semanticTags: ['files', 'drop'],
    minSize: { width: 420, height: 280 },
    defaultSize: { width: 560, height: 400 },
    scenario: 'files',
    component: (props) => <FinderApp {...props} variant="submission" />,
  },
  {
    id: 'paper',
    title: 'Paper',
    subtitle: 'Reading',
    icon: '📄',
    accent: '#c9a227',
    semanticTags: ['paper', 'read'],
    minSize: { width: 480, height: 360 },
    defaultSize: { width: 620, height: 560 },
    scenario: 'papers',
    component: PaperApp,
  },
  {
    id: 'notes',
    title: 'Notes',
    subtitle: 'Reading',
    icon: '📝',
    accent: '#f2cc8f',
    semanticTags: ['paper', 'notes'],
    minSize: { width: 280, height: 220 },
    defaultSize: { width: 340, height: 360 },
    scenario: 'papers',
    component: NotesApp,
  },
  {
    id: 'translate',
    title: 'Translate',
    subtitle: 'Reading',
    icon: '文',
    accent: '#81b29a',
    semanticTags: ['paper', 'translate'],
    minSize: { width: 280, height: 180 },
    defaultSize: { width: 320, height: 260 },
    scenario: 'papers',
    component: TranslateApp,
  },
  {
    id: 'meeting',
    title: 'Aqua Meet',
    subtitle: 'Meeting',
    icon: '📹',
    accent: '#2a9d8f',
    semanticTags: ['meeting', 'share'],
    minSize: { width: 520, height: 360 },
    defaultSize: { width: 760, height: 500 },
    scenario: 'meeting',
    component: MeetingApp,
  },
  {
    id: 'meet-chat',
    title: 'Chat',
    subtitle: 'Meeting',
    icon: '💬',
    accent: '#2a9d8f',
    semanticTags: ['meeting', 'chat'],
    minSize: { width: 240, height: 220 },
    defaultSize: { width: 280, height: 360 },
    scenario: 'meeting',
    component: ChatApp,
  },
  {
    id: 'minutes',
    title: 'Minutes',
    subtitle: 'Meeting',
    icon: '🗒',
    accent: '#e9c46a',
    semanticTags: ['meeting', 'minutes'],
    minSize: { width: 260, height: 200 },
    defaultSize: { width: 300, height: 280 },
    scenario: 'meeting',
    component: MinutesApp,
  },
  {
    id: 'speaker',
    title: 'Speaker',
    subtitle: 'Meeting',
    icon: '🎤',
    accent: '#e07a5f',
    semanticTags: ['meeting', 'speaker'],
    minSize: { width: 180, height: 160 },
    defaultSize: { width: 220, height: 200 },
    scenario: 'meeting',
    component: SpeakerApp,
  },
  {
    id: 'guide',
    title: 'AquaDraw 101',
    subtitle: 'Tutorial',
    icon: '🎓',
    accent: '#e07a5f',
    semanticTags: ['guide', 'tutorial'],
    minSize: { width: 280, height: 200 },
    defaultSize: { width: 360, height: 280 },
    scenario: 'tutorial',
    component: TutorialGuideApp,
  },
  {
    id: 'editor',
    title: 'AquaDraw',
    subtitle: 'Tutorial',
    icon: '🖌',
    accent: '#e07a5f',
    semanticTags: ['editor', 'target'],
    minSize: { width: 520, height: 360 },
    defaultSize: { width: 720, height: 480 },
    scenario: 'tutorial',
    component: EditorApp,
  },
  {
    id: 'moodboard',
    title: 'Moodboard',
    subtitle: 'Design',
    icon: '🎛',
    accent: '#9b5de5',
    semanticTags: ['reference', 'design'],
    minSize: { width: 280, height: 220 },
    defaultSize: { width: 340, height: 320 },
    scenario: 'design',
    component: MoodboardApp,
  },
  {
    id: 'canvas',
    title: 'Canvas',
    subtitle: 'Design',
    icon: '🎨',
    accent: '#9b5de5',
    semanticTags: ['canvas', 'design'],
    minSize: { width: 480, height: 320 },
    defaultSize: { width: 680, height: 460 },
    scenario: 'design',
    component: DesignCanvasApp,
  },
];

export const appHost = createAppHost(APP_CATALOG);

export const DOCK_ITEMS = [
  { id: 'finder-desktop', label: 'Finder' },
  { id: 'paper', label: 'Papers' },
  { id: 'meeting', label: 'Meet' },
  { id: 'editor', label: 'AquaDraw' },
  { id: 'canvas', label: 'Design' },
] as const;

export const SCENARIO_LAUNCH: Record<string, string[]> = {
  files: ['finder-desktop', 'finder-submission'],
  papers: ['paper', 'notes', 'translate'],
  meeting: ['meeting', 'speaker', 'meet-chat', 'minutes'],
  tutorial: ['editor', 'guide'],
  design: ['canvas', 'moodboard'],
};
